learning_templates/basic_app/urls.py
from django.conf.urls import url
from basic_app import views

# TEMPLATE TAGGING
app_name = 'basic_app'

urlpatterns = [
    url(r'^relative/$', views.relative, name='relative'),
    url(r'^other/$', views.other, name='other')
]

learning_templates/learning_templates/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from basic_app import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^basic_app/', include('basic_app.urls'))
]

learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.


def index(request):
    context_dict = {'text': 'hello world', 'number': 100}
    return render(request, 'basic_app/index.html', context_dict)


def other(request):
    return render(request, 'basic_app/other.html')


def relative(request):
    return render(request, 'basic_app/relative_url_templates.html')

learning_templates/templates/basic_app/base.html
<!DOCTYPE html>

{% load my_extras %}

<html>
<head>

    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>



    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <ul class="nav navbar-nav">
                <li><a class="navbar-brand" href="{% url 'index' %}">BRAND</a></li>
                <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
                <li><a class="navbar-link" href="{% url 'basic_app:other' %}">Other</a></li>
                <li><a class="navbar-link" href="{% url 'basic_app:relative' %}">Relative</a></li>
            </ul>
        </div>
    </nav>

    <div class="container">

        {% block body_block %}

        {% endblock %}



    </div>

</body>
</html>

learning_templates/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}



    {% block body_block %}
    <h1>Welcome to index!</h1>

    <p>The <a href="{% url 'basic_app:relative' %}">relative</a> site.</p>
    <p>The <a href="{% url 'basic_app:other' %}">other</a> site.</p>
    <h2>{{ text|cut_me:' world' }}</h2>
    <h2>{{ number|add:"99" }}</h2>

    {% endblock %}

learning_templates/templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
    {% block body_block %}

        <h1>Welcome to other!</h1>

        <p>The <a href="{% url 'basic_app:relative' %}">relative</a> site.</p>
        <!-- <p>The <a href="{% url 'admin:index' %}">admin</a> site.</p> -->
        <p>The <a href="{% url 'index' %}">index</a> site.</p>

    {% endblock %}

learning_templates/templates/basic_app/relative_url_templates.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
    {% block body_block %}

    <h1>Welcome to relative url templates site!</h1>

    <p>The <a href="{% url 'basic_app:other' %}">other</a> site.</p>
    <p>The <a href="{% url 'admin:index' %}">admin</a> site.</p>
    <p>The <a href="{% url 'index' %}">index</a> site.</p>

    {% endblock %}